import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createComponentRegistry } from "./discovery.mjs";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(scriptDir, "../..");
const packageJson = JSON.parse(readFileSync(resolve(packageRoot, "package.json"), "utf8"));
const generatedDir = resolve(packageRoot, "src/registry");
const generatedTsPath = resolve(generatedDir, "generated.ts");
const generatedJsonPath = resolve(generatedDir, "component-registry.json");
const checkOnly = process.argv.includes("--check");

const registry = createComponentRegistry({
  packageName: packageJson.name,
  packageRoot,
  packageVersion: packageJson.version,
});

const formatRecord = (record, indent) => {
  const entries = Object.entries(record);
  return entries.map(([key, value], index) => {
    const comma = index === entries.length - 1 ? "" : ",";
    return `${" ".repeat(indent)}${JSON.stringify(key)}: ${JSON.stringify(value)}${comma}`;
  });
};

const formattedRegistry = [
  "{",
  `  "schemaVersion": ${registry.schemaVersion},`,
  `  "package": ${JSON.stringify(registry.package)},`,
  '  "components": {',
  ...formatRecord(registry.components, 4),
  "  },",
  ...(Object.keys(registry.blockTemplates).length === 0
    ? ['  "blockTemplates": {},']
    : ['  "blockTemplates": {', ...formatRecord(registry.blockTemplates, 4), "  },"]),
  '  "search": {',
  '    "byGroup": {',
  ...formatRecord(registry.search.byGroup, 6),
  "    },",
  `    "byName": ${JSON.stringify(registry.search.byName)},`,
  `    "byType": ${JSON.stringify(registry.search.byType)}`,
  "  }",
  "}",
].join("\n");

const registryJson = `${formattedRegistry}\n`;
const generatedTs = `// Generated by scripts/component-registry/index.mjs. Do not edit.\nimport type { ComponentRegistry } from "./types";\n\nexport const componentRegistry = ${formattedRegistry} as const satisfies ComponentRegistry;\n\nexport type RegistryComponentName = keyof typeof componentRegistry.components;\nexport const registryComponentNames = componentRegistry.search.byName;\n\nexport type RegistryBlockTemplateName = keyof typeof componentRegistry.blockTemplates;\nexport const registryBlockTemplateNames = Object.keys(componentRegistry.blockTemplates);\n`;

const checkFile = (filePath, expected) => {
  let current = "";
  try {
    current = readFileSync(filePath, "utf8");
  } catch {
    throw new Error(`Registry output is missing: ${filePath}`);
  }
  if (current !== expected) {
    throw new Error("Registry output is stale. Run `pnpm --filter @dicehub/phi codegen:registry`.");
  }
};

if (checkOnly) {
  checkFile(generatedTsPath, generatedTs);
  checkFile(generatedJsonPath, registryJson);
  console.log(`Validated ${Object.keys(registry.components).length} generated registry entries.`);
} else {
  mkdirSync(generatedDir, { recursive: true });
  writeFileSync(generatedTsPath, generatedTs);
  writeFileSync(generatedJsonPath, registryJson);
  console.log(`Generated ${Object.keys(registry.components).length} registry entries.`);
}
