export { default as Text } from "./Text.vue";
export {
  PHI_TEXT_DEFAULT_VARIANTS,
  PHI_TEXT_STYLING,
  PHI_TEXT_VARIANTS,
  TEXT_COPY_VARIANTS,
  TEXT_DEPRECATED_HEADING_VARIANTS,
  TEXT_DEFAULT_VARIANTS,
  TEXT_ELEMENTS,
  TEXT_HEADING_VARIANTS,
  TEXT_MONOSPACE_VARIANTS,
  TEXT_SIZES,
  TEXT_VARIANTS,
  isCopyTextVariant,
  isDeprecatedHeadingTextVariant,
  isHeadingTextVariant,
  isMonospaceTextVariant,
  isTextElement,
  isTextSize,
  isTextVariant,
  resolveTextElement,
  resolveTextSize,
  resolveTextVariant,
  textVariants,
  type PhiTextVariantsProps,
  type TextCopyVariant,
  type TextDeprecatedHeadingVariant,
  type TextElement,
  type TextHeadingVariant,
  type TextMonospaceVariant,
  type TextProps,
  type TextSize,
  type TextVariant,
} from "./text";

export type TextComponentProps = import("./text").TextProps;
