import DatePickerRoot from "./DatePicker.vue";
import DatePickerCalendar from "./DatePickerCalendar.vue";
import {
  DatePickerClearTrigger,
  DatePickerContent,
  DatePickerContext,
  DatePickerControl,
  DatePickerInput,
  DatePickerLabel,
  DatePickerMonthSelect,
  DatePickerNextTrigger,
  DatePickerPositioner,
  DatePickerPresetTrigger,
  DatePickerPrevTrigger,
  DatePickerRangeText,
  DatePickerRootProvider,
  DatePickerTable,
  DatePickerTableBody,
  DatePickerTableCell,
  DatePickerTableCellTrigger,
  DatePickerTableHead,
  DatePickerTableHeader,
  DatePickerTableRow,
  DatePickerTrigger,
  DatePickerValueText,
  DatePickerView,
  DatePickerViewControl,
  DatePickerViewTrigger,
  DatePickerYearSelect,
} from "./DatePickerParts";

export const DatePicker = Object.assign(DatePickerRoot, {
  Root: DatePickerRoot,
  Calendar: DatePickerCalendar,
  ClearTrigger: DatePickerClearTrigger,
  Content: DatePickerContent,
  Context: DatePickerContext,
  Control: DatePickerControl,
  Input: DatePickerInput,
  Label: DatePickerLabel,
  MonthSelect: DatePickerMonthSelect,
  NextTrigger: DatePickerNextTrigger,
  Positioner: DatePickerPositioner,
  PresetTrigger: DatePickerPresetTrigger,
  PrevTrigger: DatePickerPrevTrigger,
  RangeText: DatePickerRangeText,
  RootProvider: DatePickerRootProvider,
  Table: DatePickerTable,
  TableBody: DatePickerTableBody,
  TableCell: DatePickerTableCell,
  TableCellTrigger: DatePickerTableCellTrigger,
  TableHead: DatePickerTableHead,
  TableHeader: DatePickerTableHeader,
  TableRow: DatePickerTableRow,
  Trigger: DatePickerTrigger,
  ValueText: DatePickerValueText,
  View: DatePickerView,
  ViewControl: DatePickerViewControl,
  ViewTrigger: DatePickerViewTrigger,
  YearSelect: DatePickerYearSelect,
});

export {
  DatePickerRoot,
  DatePickerCalendar,
  DatePickerClearTrigger,
  DatePickerContent,
  DatePickerContext,
  DatePickerControl,
  DatePickerInput,
  DatePickerLabel,
  DatePickerMonthSelect,
  DatePickerNextTrigger,
  DatePickerPositioner,
  DatePickerPresetTrigger,
  DatePickerPrevTrigger,
  DatePickerRangeText,
  DatePickerRootProvider,
  DatePickerTable,
  DatePickerTableBody,
  DatePickerTableCell,
  DatePickerTableCellTrigger,
  DatePickerTableHead,
  DatePickerTableHeader,
  DatePickerTableRow,
  DatePickerTrigger,
  DatePickerValueText,
  DatePickerView,
  DatePickerViewControl,
  DatePickerViewTrigger,
  DatePickerYearSelect,
};

export {
  datePickerAnatomy,
  parseDate,
  useDatePicker,
  useDatePickerContext,
} from "@ark-ui/vue/date-picker";
export type {
  DatePickerDateRange,
  DatePickerMode,
  DatePickerSelected,
} from "./date-picker";
export {
  DATE_PICKER_MODES,
  dateToDateValue,
  dateValueToDate,
  dateValuesToSelected,
  getRangeDayLength,
  isDatePickerMode,
  isRangeWithinDayLimits,
  resolveDatePickerTimeZone,
  selectedToDateValues,
} from "./date-picker";
export type {
  DatePickerDateRangePreset,
  DatePickerDateView,
  DatePickerFocusChangeDetails,
  DatePickerOpenChangeDetails,
  DatePickerRootProps,
  DatePickerSelectionMode,
  DatePickerValueChangeDetails,
  DatePickerViewChangeDetails,
  DatePickerVisibleRangeChangeDetails,
  DateValue as DatePickerDateValue,
} from "@ark-ui/vue/date-picker";
